; see https://docs.platformio.org/en/latest/projectconf/index.html
[platformio]
src_dir = .
include_dir = .

[env:uiapduino]
platform = ch32v
framework = ch32v003fun
board = genericCH32V003F4P6
upload_protocol = wch-link
monitor_speed = 115200
upload_flags = 
debug_tool = wch-link
debug_init_break = tbreak main
debug_speed = 4000
build_type = debug

; build_type = debug
; debug_build_flags = -O0 -g3 -fno-inline